server:
  port: 8087

spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

logging:
  level:
    com.personaltracker.ai: DEBUG
    org.springframework.ai: DEBUG