server:
  port: 8087

spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      model: gpt-3.5-turbo

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always