global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FraudGraphX API metrics
  - job_name: 'fraudgraphx-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # FraudGraphX Monitor metrics
  - job_name: 'fraudgraphx-monitor'
    static_configs:
      - targets: ['monitor:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules for fraud detection
rule_files:
  - "fraud_alerts.yml"