server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: financial-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/financial/**
          filters:
            - StripPrefix=2
            
        - id: physical-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/physical/**
          filters:
            - StripPrefix=2
            
        - id: emotional-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/emotional/**
          filters:
            - StripPrefix=2
            
        - id: career-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/career/**
          filters:
            - StripPrefix=2
            
        - id: spiritual-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/spiritual/**
          filters:
            - StripPrefix=2
            
        - id: social-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/social/**
          filters:
            - StripPrefix=2
            
        - id: ai-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG